[project]
name = "zentist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.14",
    "openai-agents[litellm]>=0.1.0",
    "python-dotenv>=1.1.1",
    "sqlmodel>=0.0.24",
]
